name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v1.1
        with:
          token: ${{ secrets.PAT }}
          repositories: 'keptn/keptn,keptn/go-utils,keptn/kubernetes-utils,keptn/keptn.github.io,keptn/spec'
          period: 90
          charts: true
          sort-by: 'COMMENTS'
